---
title: "Initial Exploration of the P/NBD Model"
author: "Mick Cooney <mickcooney@gmail.com>"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
editor: source
execute:
  message: false
  warning: false
  error: false
format:
  html:
    light: superhero
    dark: darkly
    anchor-sections: true
    embed-resources: true
    number-sections: true
    smooth-scroll: true
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-summary: "Show code"
---


```{r import_libraries}
#| echo: FALSE
#| message: FALSE

library(conflicted)
library(tidyverse)
library(scales)
library(cowplot)
library(magrittr)
library(rlang)
library(arrow)
library(fs)
library(purrr)
library(furrr)
library(glue)
library(cmdstanr)
library(brms)
library(posterior)
library(bayesplot)
library(tidybayes)
library(splines2)


source("lib_utils.R")


conflict_lst <- resolve_conflicts(
  c("magrittr", "rlang", "dplyr", "readr", "purrr", "ggplot2", "MASS",
    "fitdistrplus")
  )


options(
  width = 80L,
  warn  = 1,
  mc.cores = parallelly::availableCores()
  )


set.seed(42)
stanfit_seed <- 4000

theme_set(theme_cowplot())

plan(multisession)
```



# Load Data

We first load up the data we are using to train our dataset, as well as the
'rolled-forward' data that observes the same data a year later.

```{r load_modelling_data}
#| echo: TRUE

model_training_tbl <- read_parquet("data/model_training_small_tbl.parquet")

model_training_tbl |> glimpse()
```

We then load up the 'current' data that we use to validate our model.


```{r load_current_data}
#| echo: TRUE

model_rollforward_tbl <- read_parquet("data/model_rollforward_small_tbl.parquet")

model_rollforward_tbl |> glimpse()
```



# Build Initial Cox Model

```{r build_initial_cox_model}
#| echo: FALSE

stan_modeldir <- "stan_models"
stan_codedir  <-   "stan_code"


lapse1_brmfit <- brm(
  policy_lifetime | cens(1-lapsed) ~ gender_life1 + smoker_life1,
  data        = model_training_tbl,
  family      = cox(link = "log"),
  cores       = 4,
  seed        = 421,
  save_warmup = FALSE,
  backend     = "cmdstanr",
  save_model  = "stan_code/brm_cox.stan",

  stan_model_args = list(
    include_paths   =     "stan_code",
    pedantic        =            TRUE,
    dir             =    "stan_model"
    )
  )

summary(lapse1_brmfit)

```



